### ISSUE TITLE
Failed test

### ISSUE THREAD

**Issue by ulloaa** [nhansen/Shimmer#2]
Hello,

I am trying to build this tool on linux. However, when I run the test:

`./Build test`

I get the following error:

cd printCompCounts && make all
make[1]: Entering directory `Shimmer/printCompCounts'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `Shimmer/printCompCounts'
mkdir -p blib/bin && cp printCompCounts/printCompCounts blib/bin/
t/1_load.t .. ok   
t/2_call.t .. 3/7 
t/2_call.t .. 4/7 
   Failed test 'shimmer.pl vcf file'
   at t/2_call.t line 38.
                   'C T 458
 '
     doesn't match '(?^:^C\sT\s4(63|69|70)$)'
t/2_call.t .. 7/7 # Looks like you failed 1 test of 7.
t/2_call.t .. Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/7 subtests 

Test Summary Report

t/2_call.t (Wstat: 256 Tests: 7 Failed: 1)
  Failed test:  5
  Non-zero exit status: 1
Files=2, Tests=9, 109 wallclock secs ( 0.03 usr  0.04 sys +  4.83 cusr  2.54 csys =  7.44 CPU)
Result: FAIL
Failed 1/2 test programs. 1/9 subtests failed.

Could you please help with this?

Thanks

**Comment by nhansen** [comment]
Hi! Can you tell me what version of samtools you are using? Samtools mpileup's consensus scoring seems to change version to version, and my test suite hasn't seen this result before.

**Comment by ulloaa** [comment]
I am using samtools 1.15 but I have access to several previous versions. Is there a specific version you think I should use?

**Comment by nhansen** [comment]
Tests should pass now. Thanks again for bringing this to my attention!

**Comment by ulloaa** [comment]
Thanks, that works!
